name: Lab 1
on:
  push:
    branches:
      - "*"
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
    - name: Test
      run:
        working-directory: src/main
        sh test-mr.sh
