name: Lab 2
on:
  push:
    branches:
      - "*"
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - name: Test
        env: 
          RAFT_DEBUG: 1
        run: |
          cd src/raft
          echo $RAFT_DEBUG
          sudo go test -run 2A -race
          sudo go test -run 2B -race
          sudo go test -run 2C -race
