name: Lab 3
on:
  push:
    branches:
      - "*"
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - name: Test
        env: 
          RAFT_DEBUG: 0
        run: |
          cd src/kvraft
          go test -run 3A -race
          go test -run 3B -race