name: Lab 4
on:
  push:
    branches:
      - "*"
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - name: Test Shardmaster
        working-directory: ./src/shardmaster
        env: 
          RAFT_DEBUG: 0
        run: go test -race
      - name: Test ShardKv
        working-directory: ./src/shardkv
        env: 
          RAFT_DEBUG: 0
        run: go test -race